plugins: 
- jekyll-include-cache 
remote_theme: "mmistakes/minimal-mistakes@4.19.1"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Some security related stuff"
title_separator          : "-"
name                     : "Stipe Marinovic"
description              : "CTP/OSCE resources etc."
url                      : https://smarinovic.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google

# Social Sharing
twitter:
  username               : stipe.marinovic

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


